# This configuration file contains settings that affect the whole site.
#
# For technical reasons, this file is *not* reloaded automatically when
# you use 'bundle exec jekyll serve'. If you change this file, please
# restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# The site settings can be used inside a page via {{ site.title }},
# {{ site.email }}, and so on. You can create any custom variable
# you would like, and it will be accessible, too.

locale: "fr"
title: Les Choucas Cellois
description: >- # this means to ignore newlines until "baseurl:"
  Les Choucas Cellois, club VTT, La Celle Saint-Cloud, Yvelines, France.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: leschoucascellois
logo: "/assets/images/Logo-Montagne_64-alpha.png"

# Deploying on Github Pages requires `remote_theme:`
#       but testing offline requires `theme:`.
# See the Makefile for details.
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Look for files inside the following directories:
include: ["_pages"]

footer:
  links:
  - label: "Email"
    icon: "fa fa-envelope"
    url: "mailto:contact@leschoucascellois.org"
  - label: "Mentions légales"
    url: "/mentions_legales/"
  - label: "Agenda"
    icon: "fa fa-calendar"
    url: "https://calendar.google.com/calendar/u/0/embed?src=president@leschoucascellois.org&ctz=Europe/Paris"
